#!/bin/bash

if [ $# -eq 1 ];then
	question=$1
	read -r -p "$question:" answer

	if [ -z $answer ]
		then
		{
			colecho "No answer provided" $ERR
			exit 1
		}
	fi

	export USERANSWER=$answer
else
	errorBox "Wrong Arguments"
	usageDescription "Ask an answer to an terminal user"
	usage ". askUser question"
	example '. askUser "What Time is it?"'
	usageReturn "\$USERANSWER"
fi