#!/bin/bash
if [ $(id -u) -ne 0 ]; then
	echo "Script must be run as root."
	exit 1
fi

echo "piget framework will be installed"
echo "Installing git-core"
apt-get -q -y install git-core

mkdir /opt/piget
git clone https://github.com/pigetnet/core /opt/piget/core
if [[ $? -ne 0 ]]
	then
		echo "I wasn't able to download piget"
		echo "- Check internet connectivity"
		echo "- Check github status"
		exit 1
fi

PATH=/opt/piget/core/graphics:$PATH
PATH=/opt/piget/core/install:$PATH
PATH=/opt/piget/core/network:$PATH
PATH=/opt/piget/core/info:$PATH
chmod +x -R /opt/piget/core
nlbecho "piget installed";minibox_OK
#modifyBashStartup core




