#!/bin/bash

if [ $# -eq 1 ];then
	question=$1
	read -r -p "$question:" answer

	if [ -z $answer ]
		then
		{
			/show/colecho "No answer provided" $ERR
			exit 1
		}
	fi

	export USERANSWER=$answer
else
	/show/errorBox "Wrong Arguments"
	/show/usageDescription "Ask an answer to an terminal user"
	/show/usage ". /show/askUser question"
	/show/example '. /show/askUser "What Time is it?"'
	/show/usageReturn "\$USERANSWER"
fi