#!/bin/bash
# /show/info "[terminal] [display]"
# /show/usageDescription 'display a colored text ($GREEN/$BLUE/$PICOLOR/$INFO/$WARN/$OK/$ERR)'
# /show/example '/show/colecho "helloworld" $GREEN'

# Color available
#$GREEN
#$BLACK
#$NORMAL
#$BLUE
#$PICOLOR
#$INFO
#$OK
#$WARN
#$ERR

text=$1
color=$2
echo -ne $color
echo $text
echo -ne $NORMAL
