#!/bin/bash
# /show/info "[terminal] [display]"
# /show/usageDescription 'display a row of green slash'
# /show/example "//////////////////////"
echo -ne $OK
echo "/////////////////////"
echo -ne $NORMAL
