#!/bin/bash

if [ $# -ne 0 ] || [[ $1 == "--help" ]] || [ $(id -u) -ne 0 ];then
	/show/messagebox $0
	/show/info "[beta]"
	/show/usageDescription 'Display current folder'
	/show/usage '/show/dir'
	/show/example "/usr/bin"
else
	echo $(pwd)
fi
