#!/bin/bash
cd $1
smbname=$(/show/smbGetName)
/show/description "Display $1 on $smbname"
oldpid=$(ps axf | grep "SimpleHTTPServer" | grep -v grep | awk '{print  $1}')
kill -9 $oldpid

nohup python -m SimpleHTTPServer 314 &>/dev/null &

