#!/bin/bash
if [ $# -ne 1 ] || [[ $1 == "--help" ]] || [ $(id -u) -ne 0 ];then
	/show/messagebox $0
	/show/info "[python] [analyseScript] [alpha] [verbose]"
	/show/usageDescription 'Automatically generate an help markdown table for a script (verbose mode)'
	/show/usage '/show/help script'
	/show/example '/show/help /pi/name'
else
	if [ $# -eq 1 ];then
		script=$1
		if [ -f $script ];then
			/system/python/analyseScript.py $script --verbose
		else
			/show/errorBox "File - $1 doesn't exists"
		fi
	fi
fi

