#!/bin/bash
#Check if internet is connected
/show/nlbecho "-> INTERNET:" $OK
ping -c1 www.wikipedia.org > /dev/null 2>&1 && internet=1 || internet=0 
if [[ $internet == 1 ]]
	then
		/show/minibox_OK
		isConnected=1
	else
		/show/minibox_ERROR
		isConnected=0
fi
