#!/bin/bash
#Check if Raspberry Pi is connected to internet
if [ $# -ge 2 ] || [[ $1 == "--help" ]] || [ $(id -u) -ne 0 ];then
	/show/messagebox $0
	/show/info "[ping] [wikipedia.org] [release]"
	/show/usageDescription 'Ping a hostname or ping wikipedia.org'
	/show/usage '. /show/isConnected'
	/show/example '. /show/isConnected github.com'
	/show/return '$isConnected=1'
else 
	if [ $# -eq 1 ];then
		url=$1
		/show/nlbecho "-> $url:" $OK

	else
		/show/nlbecho "-> INTERNET:" $OK
		url="www.wikipedia.org"
	fi

	ping -c1 $url > /dev/null 2>&1 && internet=1 || internet=0
	if [[ $internet == 1 ]]
		then
			/show/minibox_OK
			isConnected=1
		else
			/show/minibox_ERROR
			isConnected=0
	fi
fi