#!/bin/bash
#Check if a package is already installed
if [ $# -ne 1 ] || [[ $1 == "--help" ]] || [ $(id -u) -ne 0 ];then
	/show/messagebox $0
	/show/info "[dpkg] [grep] [/var/lib/dpkg/status]"
	/show/usageDescription 'Check if a apt-get package is installed'
	/show/usage '/show/isInstalled'
	/show/example '/show/isInstalled samba'
	/show/return '$isInstalled=1 if installed , 0 if not'
else 
	package=$1
	check=$(grep -A1 -Fx "Package: $package" /var/lib/dpkg/status|tail -n 1)
	if [[ "$check" == "Status: install ok installed" ]];then
		isInstalled=1
	else
		isInstalled=0
	fi
fi
