#!/bin/bash
#Check if user is root
if [ $# -ne 0 ] || [[ $1 == "--help" ]] ;then
	/show/messagebox $0
	/show/info "[id]"
	/show/usageDescription 'Check if the user is root'
	/show/usage '/show/isRoot'
	/show/example '/show/isRoot'
	/show/return 'exitcode 1 if not root'
else
	if [ $(id -u) -ne 0 ]; then
		/show/errorBox
		echo "Script must be run as root."
		echo "Try 'sudo $0'"
		echo -ne $NORMAL
		/show/errorBox
		echo -ne $NORMAL
		export PIGETERROR="no root"
		exit 1
	fi
fi
