#!/bin/bash
if [ $# -ne 0 ] || [[ $1 == "--help" ]] || [ $(id -u) -ne 0 ];then
	/show/messagebox $0
	/show/info "[df] [release]"
	/show/usageDescription 'Show remaining disk space'
	/show/usage '/show/unusedDisk'
else 
	df -H|head -n2|tail -n1|awk '{print $4}'
fi
