#!/bin/bash
#You need getLine

#$1 filename
#$2 stringToSearch
#$3 stringToReplace

filename="$1"
stringToSearch2="$2"
stringToAdd="$3"

if [ $# -eq 3 ];then
	#Get Line
	. /string/getLine "$filename" "$stringToSearch2"
	lineToFind=$NewString
	if [ $lineToFind != -1 ]
	then
		. /string/getLine "$filename" "$stringToAdd"
		lineToNotFind=$NewString
		if [ $lineToNotFind -eq -1 ];then
			/show/nlbecho "Add after line $stringToSearch2 at $lineToFind $stringToAdd" $OK;/show/minibox_OK
			sed -i "${lineToFind} a $stringToAdd" $filename
		fi
	fi
else
	/show/errorBox "Wrong Arguments"
	/show/usage '/string/addAfterLineIfNotExists "Filename" "StringToSearch" "StringToAdd"'
	/show/example '/string/addAfterLineIfNotExists "/etc/hosts" "127.0.0.1" "127.0.0.1 raspberrypi"'
fi
