#!/bin/bash
#You need getLine

#$1 filename
#$2 stringToAdd

filename="$1"
stringToAdd="$2"

if [ $# -eq 2 ];then
	#Get Line
	. /string/getLine "$filename" "$stringToAdd"
	line=$NewString
	if [ $NewString != -1 ]
	then
		/show/nlbecho "Nothing to do"$OK;/show/minibox_OK
	else
		/show/nlbecho "Add line $stringToAdd" $WARN;/show/minibox_WARNING
		echo "$stringToAdd" | sudo tee -a $filename
	fi
else
	/show/errorBox "Wrong Arguments"
	/show/usage '/string/addLine "Filename" "StringToAdd"'
	/show/example '/string/addLine "/etc/apt/sources.list" "deb http://apt.pilight.org/ stable main"'
fi
