#!/bin/bash
#$1: File to read
#$2: String to search
#return $line line number if no line then -1
line=$(cat $1 |grep -n "$2"|awk '{print $1}'| head -n 1)
if [ -z $line ]
 	then
 	colecho "Line not founded" $ERR
 	line=-1
else
line=$(echo $line|cut -d: -f1)
fi
