#!/bin/bash
#$1: File to read
#$2: String to search
#return $NewString line number if no line then -1

filename=$1
stringToSearch=$2

if [ $# -eq 2 ];then
	line=$(cat $filename |grep -n "$stringToSearch"|awk '{print $1}'| head -n 1)
	if [ -z $line ];then
 		#/show/nlbecho "Line not founded" $ERR;/show/minibox_WARNING
 		export NewString=-1
	else
		export NewString=$(echo $line|cut -d: -f1)
		#/show/nlbecho "Line founded at $NewString" $OK;/show/minibox_OK
	fi
else
 	/show/errorBox "Wrong arguments"
	/show/usage "/string/getLine fileToRead StringToSearch"
	/show/example '/string/getLine "/etc/rc.local" "# Print"'
	exit 1
fi
