#!/bin/bash
#$1 filename
#$2 stringToRemove

filename="$1"
stringToRemove="$2"

if [ $# -eq 2 ];then
        #Get Line
        . /string/getLine "$filename" "$stringToRemove"
        line=$NewString
        if [ $NewString != -1 ]
        then
                /show/nlbecho "Remove Line where $stringToRemove at $line" $OK;/show/minibox_OK
                sed -i "${line}s+.*++" $filename
        else
                /show/nlbecho "No line to remove" $WARN;/show/minibox_WARNING
        fi
else
        /show/errorBox "Wrong Arguments"
        /show/usage 'removeLine "Filename" "StringToRemove"'
        /show/example 'removeLine "/etc/samba/" "netbios name"'
fi

