#!/bin/bash
#You need addAfterLine / getLine

#$1 filename
#$2 stringToSearch
#$3 stringToReplace
#$4 elseAddAfterString



filename="$1"
stringToSearch="$2"
stringToReplace="$3"
elseAddAfterString="$4"

if [ $# -eq 4 ];then
	#Get Line
	. /string/getLine "$filename" "$stringToSearch"
	line=$NewString
	if [ $NewString != -1 ]
	then
		/show/listecho "In $filename : Replace l$line -- $stringToSearch... with $stringToReplace" $OK
		sed -i "${line}s+.*+$stringToReplace+" $filename
	else
		/show/nlbecho "In $filename : Replace l? -- $elseAddAfterString" $WARN;/show/minibox_WARNING
		/string/addAfterLine "$filename" "$elseAddAfterString" "$stringToReplace"
	fi
else
	/show/errorBox "Wrong Arguments"
	/show/usage 'replaceLine "Filename" "StringToSearch" "StringToReplace" "ElseAddAfterString"'
	/show/example 'replaceLine "/etc/hosts" "127.0.0.1" "127.0.0.1 raspberrypi" "ff02::2         ip6-allrouters"'
fi
