#!/bin/bash
#You need addAfterLine / getLine

#$1 filename
#$2 stringToSearch
#$3 stringToReplace
#$4 elseAddAfterString


if [ $# -ne 4 ] || [[ $1 == "--help" ]] || [ $(id -u) -ne 0 ];then
	/show/info "[beta] [string] [avahi] [bonjour]"
	/show/usageDescription "Change name in /etc/hosts and /etc/hostname"
	/show/usage '$0 "Filename" "StringToSearch" "StringToReplace" "ElseAddAfterString"'
	/show/example '$0 "/etc/hosts" "127.0.0.1" "127.0.0.1 raspberrypi" "ff02::2         ip6-allrouters"'
else
	filename="$1"
	stringToSearch="$2"
	stringToReplace="$3"
	elseAddAfterString="$4"

	#Get Line
	. /string/getLine "$filename" "$stringToSearch"
	line=$NewString
	if [ $NewString != -1 ]
	then
		# /show/listecho "In $filename : Replace l$line -- $stringToSearch... with $stringToReplace" $OK
		sed -i "${line}s+.*+$stringToReplace+" $filename
	else
		# /show/nlbecho "In $filename : Replace l? -- $elseAddAfterString" $WARN;/show/minibox_WARNING
		/string/addAfterLine "$filename" "$elseAddAfterString" "$stringToReplace"
	fi
fi
