#!/bin/bash
#You need getLine

#$1 filename
#$2 stringToSearch
#$3 stringToReplace

filename="$1"
stringToSearch="$2"
stringToReplace="$3"

if [ $# -eq 3 ];then
	#Get Line
	. getLine "$filename" "$stringToSearch"
	line=$NewString
	if [ $NewString != -1 ]
	then
		nlbecho "Replace Line $stringToSearch at $line with $stringToReplace" $OK;minibox_OK
		sed -i "${line}s+.*+$stringToReplace+" $filename
	fi
else
	errorBox "Wrong Arguments"
	usage 'replaceLine "Filename" "StringToSearch" "StringToReplace"'
	example 'replaceLine "/etc/hosts" "127.0.0.1" "127.0.0.1 raspberrypi"'
fi
