#!/bin/bash
#Check if arguments correctly set

if [[ $# -eq 1 ]]; then
	#Conform to netbios standard
	. /string/stripAccents $1 # No accent
	. /string/upperToLower $NewString #No case
	. /string/ToAlphaNumeric $NewString #No special characters
	. /string/Trim $NewString #No white space
	NewString=$(echo $NewString|cut -c1-16) #No more than 16 characters

	#Check if variable is empty
	if [[ -z $NewString ]]; then
		/show/listecho "No name provided RESET TO DEFAULT" $WARN
		export NewString="raspberrypi"
	else
		export NewString=$NewString
	fi
else
	/show/listecho "No name provided : RESET TO DEFAULT" $WARN
	export NewString="raspberrypi"
fi


