#!/bin/bash

# If no arguments is provided we check if it was set inside bootstrap
description "Naming your Raspberry pi"

echo "This will configure"
listecho "SAMBA -- For Windows"
listecho "AVAHI -- For MacOS"
listecho "DNSMASQ -- DNS small Server"

description "This will erase all configuration for samba/dnsmasq!"
echo "If you want to just rename your raspberry pi type renameMe"

if [ $# -eq 0 ]
then
	if [ -f /boot/piget/config/name.txt ]
	then
		messagebox "BOOTSTRAP CONFIGURATION FOUNDED"
		NEW_HOSTNAME=$(cat /boot/piget/config/name.txt)
	else
		errorBox "No enough Arguments and no configuration"
		usage "renameMe newname"
		example "renameMe raspberrypi"
		exit 1
	fi
fi

#If an arguments is provided we will use it
if [ $# -eq 1 ]
then
	NEW_HOSTNAME=$1
fi

#Convert Name to Netbios convention to ensure compatibility
#If no hostname was provided will be reset to default (raspberrypi)
. ToNetbios "$NEW_HOSTNAME"
NEW_HOSTNAME=$NewString

clear
messagebox "New name will be $NEW_HOSTNAME"
sleep 5


###### HOSTNAME / HOSTS
installer avahi-daemon
resetHost $NEW_HOSTNAME

###### SAMBA

description "Checking PreRequisites"
installer samba
installer smbclient

description "Resetting samba configuration to just broadcast name"
resetSamba "$NEW_HOSTNAME"


########## DNSMASQ

installer dnsmasq
hostname $NEW_HOSTNAME
resetDnsmasq "$NEW_HOSTNAME"

