#!/bin/bash

# If no arguments is provided we check if it was set inside bootstrap
description "Naming your Raspberry pi"

echo "This will configure"
listecho "SAMBA -- For Windows"
listecho "AVAHI -- For MacOS"

if [ $# -eq 0 ]
then
	if [ -f /boot/piget/config/name.txt ]
	then
		messagebox "BOOTSTRAP CONFIGURATION FOUNDED"
		NEW_HOSTNAME=$(cat /boot/piget/config/name.txt)
	else
		errorBox "No enough Arguments and no configuration inside /boot/piget/config/name.txt"
		usage "PiNameMe newname"
		example "PiNameMe raspberrypi"
		exit 1
	fi
fi

#If an arguments is provided we will use it
if [ $# -eq 1 ]
then
	NEW_HOSTNAME=$1
	echo $NEW_HOSTNAME > /boot/piget/config/name.txt
fi

#Convert Name to Netbios convention to ensure compatibility
#If no hostname was provided will be reset to default (raspberrypi)
. ToNetbios "$NEW_HOSTNAME"
NEW_HOSTNAME=$NewString

clear
description "This will erase samba configuration!"
echo "If you want to rename your raspberry pi type PiRename"
messagebox "New name will be $NEW_HOSTNAME"
sleep 5

###### HOSTNAME / HOSTS
installer avahi-daemon
resetHost $NEW_HOSTNAME
restarter avahi-daemon

###### SAMBA
description "Checking PreRequisites"
installer samba
installer smbclient

description "Resetting samba configuration to just broadcast name"
replaceLine "/etc/samba/smb.conf" "netbios name =" "        netbios name = $NEW_HOSTNAME" "\[global\]"
restarter samba
########## DNSMASQ

#installer dnsmasq

#resetDnsmasq "$NEW_HOSTNAME"

