#!/bin/bash
description "Resetting samba"
installer samba

if [ -f /etc/samba/smb.conf ];then

#Check if hostname is compatible with netbios
. ToNetbios $1
NEW_HOSTNAME=$NewString

description "Change /etc/samba/smb.conf to $NEW_HOSTNAME"
#Backup smb.conf
autoBackup /etc/samba/smb.conf

cat <<\EOF > /etc/samba/smb.conf &&
#======================= Global Settings =======================
[global]
        workgroup = WORKGROUP
        browseable = yes
#======================= Name =========================
        #Name of your Raspberry Pi
        netbios name = TOREPLACE
EOF
replaceLine "/etc/samba/smb.conf" "netbios name =" "        netbios name = $NEW_HOSTNAME" "\[global\]"

restarter samba
console
cat /etc/samba/smb.conf
console

else
	nlbecho "Samba is not installed" $WARN;minibox_SKIP
fi

