#!/bin/bash

description "Resetting hostname"

#Check if hostname is compatible with netbios
. ToNetbios $1
NEW_HOSTNAME=$NewString

description "Change /etc/hostname to $NEW_HOSTNAME"
autoBackup /etc/hostname
echo $NEW_HOSTNAME > /etc/hostname
console
cat /etc/hostname
console

description "Reset /etc/hosts"
autoBackup /etc/hosts
cat << EOF /etc/hosts &&
127.0.0.1       localhost
::1             localhost ip6-localhost ip6-loopback
fe00::0         ip6-localnet
ff00::0         ip6-mcastprefix
ff02::1         ip6-allnodes
ff02::2         ip6-allrouters

127.0.1.1       TOREPLACE
EOF
replaceLine "/etc/hosts" "127.0.1.1" "127.0.1.1   $NEW_HOSTNAME" "ff02::2         ip6-allrouters"

console
cat /etc/hosts
console
hostname $NEW_HOSTNAME
