#!/bin/bash
description "Resetting dnsmasq"

ipaddress=$(ipAddress)

if [ -f /etc/dnsmasq.conf ];then

#Check if hostname is compatible with netbios
. ToNetbios $1
NEW_HOSTNAME=$NewString

description "Change /etc/dnsmasq.conf to $NEW_HOSTNAME"
autoBackup /etc/dnsmasq.conf

cat <<\EOF > /etc/dnsmasq.conf &&
addn-hosts=/boot/piget/config/hosts.txt
expand-hosts
domain=home
local-ttl=300
EOF

console
cat /etc/dnsmasq.conf
console

description "reset /boot/piget/config/hosts.network to $ipaddress	$NEW_HOSTNAME"
mkdir -p /boot/piget/config
autoBackup /boot/piget/config/hosts.txt
echo "$ipaddress	$NEW_HOSTNAME" > /boot/piget/config/hosts.txt
console
cat /boot/piget/config/hosts.txt
console

restarter dnsmasq
description "You must add $ipaddress as a altenative dns server"
listecho "Directly on your computer/smartphone"
listecho "On your router/box/dhcp server"

else
	nlbecho "dnsmasq is not installed" $WARN;minibox_SKIP
fi


