#!/bin/bash
if [[ -f /etc/samba/smb.conf ]]
	then
		smbname=$(cat /etc/samba/smb.conf |grep "netbios name = ")
	if [[ $? == 0 ]]
	then
		echo $smbname|sed 's/netbios name = //'
	else
	ipAddress
fi
else
	ipAddress
fi
