#!/bin/bash
#Add a warning message (experimental)


name=$1
filename=/boot/piget/config/warning/$1.txt
warning=$2
action=$3

if [ $# -eq 3 ];then
	description "Add a warning message at $filename"
	
	createDir "/boot/piget/config/warning"
	
	rm -f $filename
	touch $filename
	echo "____________ $name _____________________" >> $filename
	echo "WARNING: $warning" >> $filename
	echo "ACTION: $action" >> $filename
	echo "-----------------------------------" >> $filename
	echo "" >> $filename
	cat $filename
else
	errorBox "Wrong Arguments"
	usageDescription "Add a warning in /boot/piget/warning/"
	usage "addWarning filename warning action"
	example 'addWarning "rootunsecure" "Secure root account" "passwd root"'
fi
