#!/bin/bash
username=$1
repo=$2
curl -silent https://api.github.com/repos/$username/$repo|grep "Not Found"

if [ $? -eq 1 ];then
	nlbecho "Repo exists" $OK;minibox_OK
	exit 0
else
	errorBox "$? - Repo $username/$repo doesn't exists"
	exit 1
fi
