#!/bin/bash
#Check if user is root
if [ $(id -u) -ne 0 ]; then
	errorBox
	echo "Script must be run as root."
	echo "Try 'sudo $0'"
	echo -ne $NORMAL
	errorBox
	echo -ne $NORMAL
	export PIGETERROR="no root"
	exit 1
fi
