#!/bin/bash
# Add a repository
#http://askubuntu.com/questions/197564/how-do-i-add-a-line-to-my-etc-apt-sources-list


if [ $# -ge 1 ]
then
	repo=$1
	key=$2
	/show/description "Add custom repositories $repo into sources.list"
	/system/autoBackup /etc/apt/sources.list
	/string/addLine "/etc/apt/sources.list" "$repo"
	/show/file /etc/apt/sources.list
	if [ $# -eq 2 ];then
		/show/description "Add key $key"
		wget -O - $key | apt-key add -
	fi
else
	/show/errorBox "Wrong Arguments"
	/show/usageDescription "add an APT Repository"
	/show/usage "/system/addAptRepository repoUrl keyUrl"
	/show/example '/system/addAptRepository "deb http://apt.pilight.org/ stable main" "http://apt.pilight.org/pilight.key"'
fi

