#!/bin/bash
/show/description "Add root user"
if [ -e /boot/piget/config/rootpassword.txt ]
then
	/show/listecho "Found a password in /boot/piget/config/rootpassword.txt" $OK
	password=$(cat /boot/piget/config/rootpassword.txt)
	echo "root:$password" |chpasswd
	if [ $? -eq 0 ];then
		/show/listecho "Remove /boot/piget/config/rootpassword.txt" $OK
		rm -f /boot/piget/config/rootpassword.txt
		/show/nlbecho "-> Root Password changed" $OK;/show/minibox_OK
	else
		/show/nlbecho "-> Wrong root password" $OK;/show/minibox_ERROR
	fi
else
	/show/nlbecho "-> No default password founded in /boot/piget/config/rootpassword.txt" $WARN
	/show/minibox_WARNING
	/show/listecho "Enter your password" $OK
	passwd root
fi
