#!/bin/bash
#Download a single file on gihub repositories
#$1 username
#$1 reponame
#$3 dir/filename
#$4 destination

if [ $# -eq 2 ]
then
	url=$1
	destination=$2

/show/nlbecho "-> HTTP: $url ==> $destination " $OK

rm -f /tmp/wget.temp
wget $url -O /tmp/wget.temp --no-check-certificate > /dev/null 2>&1
wgeterror=$?
/system/wgetErrorManager $wgeterror /tmp/wget.temp
if [ -s "/tmp/wget.temp" ]
then
	mv /tmp/wget.temp $destination
	/show/minibox_OK
else
	rm -f /tmp/wget.temp
	/show/minibox_ERROR
	read
	exit 1
	fi
else
	/show/errorBox "1 - Wrong arguments"
	/show/usage "/system/downloadFile url destination"
	/show/example "/system/downloadFile http://www.foobar.com/file.zip /tmp/foobar.zip"
	exit 1
fi