#!/bin/bash
#Clone a gitrepo on a custom repo on github
#$1 repo/file

if [ $# -eq 2 ]
then
	username=$1
	reponame=$2
else
	/show/errorBox "1 - Wrong arguments"
	/show/usage "downloadModule username reponame"
	/show/example "downloadModule pigetnet leds"
	exit 1
fi

/show/description "Downloading $username/$reponame into /opt/piget/$reponame"
/show/console
/show/isGithubRepo $username $reponame
if [ $? -eq 0 ]
then
	rm -rf /opt/piget/$reponame
	/system/gitcloner $username/$reponame /opt/piget/$reponame
else
	exit 1
fi
/show/console

