#!/bin/bash
#Clone a gitrepo on pigetnet on github
#$1 repo/file

if [ $# -ge 2 ] || [[ $# -eq 0 ]] || [[ $1 == "--help" ]] || [ $(id -u) -ne 0 ];then
    /show/messagebox "$0"
    /show/info '[dev] [beta]'
    /show/usageDescription 'Download a module on github.com'
    /show/usage "$0 module or user/module"
    /show/example "$0 samba or maditnerd/example"
else
    reponame=$1
    if [[ $reponame == *"/"* ]];then
        #echo "Custom detected"
        username=${reponame%/*}
        reponame=${reponame#*/}
    else
        username=$(cat /user/settings/pi/repo.txt)
    fi
    /show/description "[GITHUB] $username/$reponame => /do/$reponame"
    /show/isGithubRepo $username $reponame

    if [ $? -eq 0 ]
    then
        /system/gitcloner $username/$reponame /opt/piget/$reponame
    else
        /show/colecho "No repo founded" $ERR
        exit 1
    fi
fi