#!/bin/bash
# Install/Update WiringPi
if [ $# -ge 1 ] || [[ $1 == "--help" ]] || [ $(id -u) -ne 0 ];then
  /show/messagebox "$0"
  /show/info '[beta]'
  /show/usageDescription 'Download and install WiringPi (to manage GPIO)'
  /show/usage "$0"
else
	if [ ! -d "/opt/wiringPi" ];then
			/show/listecho "[WiringPi] Installation" $OK
			/system/install git-core

			git clone -q git://git.drogon.net/wiringPi /opt/wiringPi

			cd /opt/wiringPi/
			./build > /tmp/build_wiringPi.log
			/show/colecho "installed" $OK
	else
		/show/listecho "[WiringPi] Check Update" $OK
		cd /opt/wiringPi;./newVersion
	fi
fi
