#!/bin/bash
# https://raymii.org/s/tutorials/Silent-automatic-apt-get-upgrade.html
#export DEBIAN_FRONTEND=noninteractive
export DEBIAN_PRIORITY=critical
PACKAGE=$1
. /show/isInstalled $PACKAGE

if [ $# -eq 1 ] && [[ $1 != "--help" ]];then
#IS THE PACKAGE ALREADY INSTALLED ?
if [[ $isInstalled -eq 0 ]];then
	/show/nlbecho "-> Install: $PACKAGE" $OK
	#debconf-apt-progress -- apt-get -q -y -o "Dpkg::Progress-Fancy=1" -o "Dpkg::Options::=--force-confdef" -o "Dpkg::Options::=--force-confold" install "$PACKAGE"
	#apt-get -q -y -o "Dpkg::Options::=--force-confdef" -o "Dpkg::Options::=--force-confold" install "$PACKAGE"
	debconf-apt-progress -- apt-get install -q -y "$PACKAGE"
	. /show/isInstalled $PACKAGE
	#WAS THE PACKAGE INSTALLED ?
	if [[ $isInstalled -eq 1 ]];then
		/show/minibox_OK
	else
		. /show/isPackage
		if [[ $isPackage == 0 ]];then
			/show/nlbecho "-> PACKAGE NOT FOUNDED" $WARN;/show/minibox_WARNING
			read
		else
			/show/minibox_ERROR
			/show/errorBox "Diagnosis : Installation failed"
			/show/colecho "-> Package state:$check" $ERR
			/show/colecho "-> apt-get install diagnosis" $ERR
			apt-get install
			#aptitude reinstall debconf 
			/show/isConnected
			/show/colecho "UNABLE TO CONTINUE" $ERR
			read
		fi
		
	fi
# else
	# /show/listecho "Install: $PACKAGE [SKIPPED]" $INFO
fi
else
	echo "HELP REQUIRED"
fi
