#!/bin/bash
# Install/Update WiringPi
# http://www.orangepi.org/Docs/WiringPi.html
if [ $# -ge 1 ] || [[ $1 == "--help" ]] || [ $(id -u) -ne 0 ];then
  /show/messagebox "$0"
  /show/info '[beta] [orangepi]'
  /show/usageDescription 'Download and install WiringPi (to manage GPIO)'
  /show/usage "$0"
else
	hardware=$(/pi/getBoard)

	if [ ! -d "/opt/wiringPi" ];then
			/show/listecho "[WiringPi] Installation" $OK
			/system/install git-core



			if [[ $hardware == "orangepi" ]];then
				git clone -q https://github.com/zhaolei/WiringOP.git -b h3 /opt/wiringPi
			else
				git clone -q git://git.drogon.net/wiringPi /opt/wiringPi
			fi

			cd /opt/wiringPi/
			./build > /tmp/build_wiringPi.log
			/show/colecho "installed" $OK
	else
		/show/listecho "[WiringPi] Check Update" $OK

		if [[ $hardware == "orangepi" ]];then
			echo "Update is not implemented on orangePi"
		else
			cd /opt/wiringPi;./newVersion
		fi
	fi
fi
