#!/bin/bash
/show/description "Removing user $1"
if id -u "$1" >/dev/null 2>&1; then
	userdel $1
	rm -rf /home/bob
else
        /show/colecho "User doesn't exists";/show/minibox_SKIP
        /show/listUsers
fi
