#!/bin/bash
filename=$2
wgeterror=$1
if [[ -f $filename ]]
        then

		case $wgeterror in
			0)
			
			;;

			2)
			/show/listecho "Wrong wget commands" $ERR
			;;

			*)
			rm -f $filename
			/show/listecho "File not founded" $ERR
			;;
		esac
else
        /show/listecho "Wrong filename" $ERR
fi
