#!/bin/bash
if [ $# -eq 1 ]
then
	newpath=$1
	description "Add $newpath to /root/.bashrc"
	replaceLine "/root/.bashrc" "PATH=$newpath:\$PATH" "PATH=$newpath:\$PATH" "PATH=/opt/piget/core/string:\$PATH"
	PATH=$newpath:$PATH
else
	errorBox "Wrong Arguments"
	usage 'addPath "newPath"'
	example 'addPath "/opt/usercode"'
fi
