#!/bin/bash
#
if [ $# -eq 1 ]
then
	newpath=$1
	description "Add $newpath to /root/.bashrc"
	replaceLine "/root/.bashrc" "PATH=\$PATH:$newpath" "PATH=\$PATH:$newpath" "PATH=\$PATH:/opt/piget/core/string"
	export PATH=$PATH:$newpath
else
	errorBox "Wrong Arguments"
	usageDescription "Add a path into /root/.bashrc"
	usage 'addPath "newPath"'
	example 'addPath "/opt/usercode"'
fi
