#!/bin/bash
description "Add Root User"
if [ -e /boot/piget/config/rootpassword.txt ]
then
	messagebox "Founded a rootpassword in boot"
	password=$(cat /boot/piget/config/rootpassword.txt)
	echo "root:$password" |chpasswd
	messagebox "Removing bootstrapped password"
	rm -f /boot/piget/config/rootpassword.txt
	colecho "Password succesfully changed";minibox_OK
else
	passwd root
fi
