#!/bin/bash
#Automatically backup a file into /boot/piget/backups
filename=$1
basename=$(basename $filename)
timestamp=$(date +%Y%m%d)'_'$(date +%H%M%S)

colecho "THIS WILL OVERWRITE/ERASE $filename !" $ERR
colecho "(A backup will be made at /boot/piget/backups/$basename.backup.$timestamp)" $WARN
mkdir -p /boot/config/backups
cp $filename /boot/config/backups/$basename'.backup.'$timestamp
