#!/bin/bash
messagebox "Create directory $1"
if [ -d "$directory" ]
then
nlbecho "CREATE DIRECTORY $directory"
minibox_SKIP
else
mkdir -p $1
	if [[ $? == 0 ]]
		then
		nlbecho "CREATE DIRECTORY"
		minibox_OK
		else
		errorBox $?
		echo "CANNOT CREATE DIRECTORY"
		errorBox " "
		exit 0
	fi
fi
