#!/bin/bash
#Create a directory recursively (if it doesn't exists)
if [ -d "$directory" ]
then
	nlbecho "CREATE DIRECTORY $directory"
	minibox_SKIP
else
	mkdir -p $1
	if [[ $? == 0 ]]
		then
		nlbecho "CREATED DIRECTORY"
		minibox_OK
		else
		errorBox $?
		echo "CANNOT CREATE DIRECTORY"
		errorBox " "
		exit 0
	fi
fi
