#!/bin/bash
#Clone a gitrepo on a custom repo on github
#$1 repo/file

if [ $# -eq 2 ]
then
	username=$1
	reponame=$2
else
	errorBox "1 - Wrong arguments"
	usage "downloadModule username reponame"
	example "downloadModule pigetnet leds"
	exit 1
fi

description "Downloading $username/$reponame into /opt/piget/$reponame"
console
	isGithubRepo $username $reponame
	if [ $? -eq 0 ]
	then
		rm -rf /opt/piget/$reponame
		gitcloner $username/$reponame /opt/piget/$reponame
		addPath /opt/piget/$reponame
		export PATH=/opt/piget/$reponame:$PATH
	else
		exit 1
	fi
console

