#!/bin/bash
#Download a simple file on pigetnet gihub repositories
#$1 repo/file
#$2 dir/filename

if [ $# -eq 3 ]
then
	reponame=$1
	source=$2
	destination=$3
else
	errorBox "1 - Wrong arguments"
	usage "downloadFile reponame filename destination"
	example "downloadFile core graphics/colecho /tmp/test.sh"
	exit 1
fi


description "Downloading $reponame/$source ==> $destination "

console
	rm -f /tmp/wget.temp
	wget https://raw.githubusercontent.com/pigetnet/$reponame/master/$source -O /tmp/wget.temp
	wgeterror=$?
	wgetErrorManager $wgeterror /tmp/wget.temp
	if [ -s "/tmp/wget.temp" ]
	then
		mv /tmp/wget.temp $destination
	else
		rm -f /tmp/wget.temp
		echo "Here is a list of available files"
		curl -s https://github.com/pigetnet/$reponame/ | grep js-directory-link | sed 's|.* title="\(.*\)".*|\1|'
		exit 1
	fi
console
