#!/bin/bash
#Clone a gitrepo on pigetnet on github
#$1 repo/file

if [ $# -eq 1 ]
then
	reponame=$1
else
	errorBox "1 - Wrong arguments"
	usage "downloadModule reponame"
	example "downloadModule samba"
	exit 1
fi

description "Downloading $reponame into /opt/piget/$reponame"
console
	isGithubRepo "pigetnet" $reponame
	if [ $? -eq 0 ]
	then
		gitcloner pigetnet/$reponame /opt/piget/$reponame
		addPath /opt/piget/$reponame
		export PATH=/opt/piget/$reponame:$PATH
	else
		colecho "No repo founded" $ERR
		exit 1
	fi
console
