#!/bin/bash
#Download a simple file on pigetnet account 
#$1 repo/file
#$2 dir/filename

if [ $# -eq 4 ]
then
	username=$1
	reponame=$2
	source=$3
	destination=$4
else
	errorBox "1 - Wrong arguments"
	usage "downloadFileCustom username reponame filename destination"
	example "downloadFileCustom  graphics/colecho /tmp/test.sh"
	exit 1
fi


description "Downloading $username/$reponame/$source ==> $destination "

console
	rm -f /tmp/wget.temp
	wget https://raw.githubusercontent.com/$username/$reponame/master/$source -O /tmp/wget.temp
	wgeterror=$?
	wgetErrorManager $wgeterror /tmp/wget.temp
	if [ -s "/tmp/wget.temp" ]
	then
		mv /tmp/wget.temp $destination
	else
		rm -f /tmp/wget.temp
	fi
console
