#!/bin/bash
export DEBIAN_FRONTEND=noninteractive
messagebox "INSTALL: $1"

isInstalled $1
#IS THE PACKAGE ALREADY INSTALLED ?
if [[ $? == 1 ]]
	then
		console
		apt-get -q -y install "$1"
		aptgetErrorLevel=$?
		if [[ $aptgetErrorLevel -ne 0 ]]
			then
				errorBox "apt-get install failed -" $aptgetErrorLevel
				colecho "SCRIPT KILLED" $ERR
				kill -9 `ps --pid $$ -oppid=`;exit
		fi
		console
		isInstalled $1
#WAS THE PACKAGE INSTALLED ?
	if [[ $? == 0 ]]
		then
			echo -ne "RESULT: $1"
			minibox_OK
		else
			echo -ne "RESULT: $1"
			minibox_ERROR
			read
		fi
	else
		echo -ne "RESULT: $1"
		minibox_SKIP
	fi
