#!/bin/bash
#Update Piget Module
#http://stackoverflow.com/questions/4000613/bash-for-each-directory
#http://stackoverflow.com/questions/1125968/force-git-to-overwrite-local-files-on-pull

for D in /opt/piget/*; do
	if [ -d "${D}" ]; then
		moduleName=$(basename "${D}")
		echo $moduleName   # your processing here
		git --work-tree=/opt/piget/$moduleName --git-dir=/opt/piget/$moduleName/.git pull origin master
	fi
done
