#!/bin/bash
#Clone a gitrepo on pigetnet on github
#$1 repo/file

if [ $# -eq 1 ]
then
	reponame=$1
else
	errorBox "1 - Wrong arguments"
	usage "removeModule reponame"
	example "removeModule samba"
	exit 1
fi

description "Removing /opt/piget/$reponame"
console
if [ -d "/opt/piget/$reponame" ];then
	if [ ! -d "/opt/piget/$reponame/core/install" ];then
		if [ ! -d "/opt/piget/$reponame/piget" ];then
			if [ ! -d "/opt/piget/$reponame/etc" ];then
				rm -rf /opt/piget/$reponame
				removePath /opt/piget/$reponame
			else
				colecho "You were really close to delete everything" $ERR
			fi
		else
			colecho "You were really close to delete piget" $ERR
		fi
	else
		colecho "No module specified" $ERR
	fi
else
	colecho "Directory does not exists" $ERR
	exit 1
fi
console
