#!/bin/bash
if [ $# -eq 1 ]
then
	oldpath=$1
	description "Remove $oldpath from .bashrc"
	removeLine "/root/.bashrc" "PATH=$oldpath:\$PATH"
else
	errorBox "Wrong Arguments"
	usage 'addPath "newPath"'
	example 'addPath "/opt/usercode"'
fi
