#!/bin/bash
# Install/Update WiringPi

description "WiringPi Pi Installation"
installer git-core


messagebox "Confirm installation path"
nlbecho "By default WiringPi will be installed in" 
colecho "/opt/wiringpi/" $ERR

cd /opt/
git clone git://git.drogon.net/wiringPi wiringPi
messagebox "Build wiringpi"
console
cd opt/wiringPi/
./build
console
linebreak
nextline
nextline
colecho "WiringPi installed!" $WARN
echo "To compile a C++ program with it"
echo "Type:"
colecho "gcc program.cpp -o program -lwiringPi" $PICOLOR
thank