#!/bin/bash
# Install/Update WiringPi

description "WiringPi Pi Installation"
installer git-core

nlbecho "By default WiringPi will be installed in" 
colecho "/opt/wiringPi/" $ERR

rm -rf /opt/wiringPi
cd /opt/
git clone git://git.drogon.net/wiringPi wiringPi

messagebox "Build wiringpi"
console
cd opt/wiringPi/
./build
console

colecho "WiringPi installed!" $WARN
echo "To compile a C++ program with it"
echo "Type:"
colecho "gcc program.cpp -o program -lwiringPi" $PICOLOR
