#!/bin/bash
#Install nodejs (adafruit installer)
if [ $# -ne 0 ] || [[ $1 == "--help" ]] || [ $(id -u) -ne 0 ];then
	/show/messagebox "$0"
	/show/info '[beta] [node] [nodesource]'
	/show/usageDescription 'Install lastest nodejs from nodesource (https://github.com/nodesource/distributions)'
	/show/usage "$0"
else
	if [ ! -e /usr/local/bin/node ];then
		curl -sL https://deb.nodesource.com/setup_7.x | bash -
		/system/install nodejs
		nodeversion=$(node -v)
		/show/listecho "Node version $nodeversion" $OK
	else
		/show/messagebox "NodeJS already installed" 
	fi
fi
