#!/bin/bash
if [ $# -ge 2 ] || [[ $# -eq 0 ]] || [[ $1 == "--help" ]] || [ $(id -u) -ne 0 ];then
  /show/messagebox "$0"
  /show/info '[beta]'
  /show/usageDescription 'Download a module at github.com/pigetnet and install it'
  /show/usage "$0 module"
  /show/example "$0 samba"
else
	/system/downloadModule $1
	if [ -e /do/$1/install ];then
		/do/$1/install
	fi
fi