#!/bin/bash
if [ $# -ge 3 ] || [ $# -le 1 ] || [[ $1 == "--help" ]] || [ $(id -u) -ne 0 ];then
  /show/messagebox "$0"
  /show/info '[beta] [2 args]'
  /show/usageDescription 'create a link to a command inside /usr/local/bin'
  /show/usage "$0 command link"
  /show/example "$0 /pi/ledOn turn_on_led"
else
	scriptToLink=$1
	link=$2
	if [[ -f $scriptToLink ]];then
		ln -sv $scriptToLink /usr/local/bin/$link
	fi
fi

