#!/bin/bash
if [ $# -ne 0 ] || [[ $1 == "--help" ]] || [ $(id -u) -ne 0 ];then
  /show/messagebox "$0"
  /show/info '[beta] [github]'
  /show/usageDescription 'Display availbles modules for piget on github'
  /show/usage "$0"
else
	/show/description "Availables modules"
	/system/getRepo "pigetnet"
fi
