#!/bin/bash
if [ $# -eq 1 ] && [[ $1 == "--help" ]];then
	/show/messagebox "/pi/project"
	/show/usageDescription "Launch install script at /boot/piget/scripts/install.sh"
	/show/usage '/pi/project'
	/show/example '/pi/project'
else
	/show/description "Starting project"
	if [ -e /boot/piget/scripts/install.sh ];then
		/show/listecho "Launching /boot/piget/scripts/install.sh" $OK
		chmod +x /boot/piget/scripts/install.sh
		/boot/piget/scripts/install.sh
	else
		/show/errorBox "No installer founded at /boot/piget/scripts/install.sh"
	fi
fi

