#!/bin/bash
# 

# If no arguments is provided we check if it was set inside bootstrap
if [ $# -ge 2 ] || [[ $1 == "--help" ]] || [ $(id -u) -ne 0 ];then
    /show/messagebox "$0"
	/show/info "[beta]"
	/show/usageDescription "Rename your Raspberry Pi using avahi/samba"
	/show/usage "$0 [newname] (default:/user/settings/pi/name.txt)"
	/show/example "$0 raspberrypi"
else

	OLD_HOSTNAME=$(/show/smbGetName)
	NEW_HOSTNAME=$OLD_HOSTNAME
	#If no arguments is given
	if [ $# -eq 0 ];then
		# Get hostname from /boot/piget/config/name.txt
		if [ -f /user/settings/pi/name.txt ];then
			NEW_HOSTNAME=$(cat /user/settings/pi/name.txt)
		fi
	else
		#If a name is provided
		if [ $# -eq 1 ];then	
			NEW_HOSTNAME=$1			
		fi
	fi

	if [ -n "$NEW_HOSTNAME" ];then

		# Check if samba and avahi is installed
		/system/install samba
		/system/install avahi-daemon

		#Save hostname
		#Convert Name to Netbios convention to ensure compatibility
		#If no hostname was provided will be reset to default (raspberrypi)
		. /string/ToNetbios "$NEW_HOSTNAME"
		NEW_HOSTNAME=$NewString
		
		#Copy new hostname inside /boot/piget/config/name.txt
		echo $NEW_HOSTNAME > /user/settings/pi/name.txt

		if [ $# -ne 0 ];then
			/show/description "[Name] $OLD_HOSTNAME --> $NEW_HOSTNAME"
			echo -e "Type $ERR /pi/start $NORMAL to refresh $OK name $NORMAL"
		fi
		
		###### HOSTNAME / HOSTS
		/net/resetHost $NEW_HOSTNAME

		###### SAMBA
		# /show/listecho "Samba Name : $NEW_HOSTNAME" $1
		/string/replaceLine "/etc/samba/smb.conf" "netbios name =" "        netbios name = $NEW_HOSTNAME" "\[global\]"
		/system/restart samba
	
	fi
fi