#!/bin/bash
#Update Piget Module
#http://stackoverflow.com/questions/4000613/bash-for-each-directory
#http://stackoverflow.com/questions/1125968/force-git-to-overwrite-local-files-on-pull

for D in /opt/piget/*; do
	if [ -d "${D}" ]; then
		moduleName=$(basename "${D}")
		/show/listecho "UPDATE : $moduleName" $OK   # your processing here
		git --work-tree=/opt/piget/$moduleName --git-dir=/opt/piget/$moduleName/.git fetch --all > /dev/null 2>&1 
		/show/listecho "FETCH : $?" $OK
		git --work-tree=/opt/piget/$moduleName --git-dir=/opt/piget/$moduleName/.git reset --hard origin/master > /dev/null 2>&1 
		/show/listecho "RESET : $?" $OK
		git --work-tree=/opt/piget/$moduleName --git-dir=/opt/piget/$moduleName/.git pull origin master > /dev/null 2>&1 
		/show/listecho "PULL  : $?" $OK
	fi
done

