#!/bin/bash

if [ $# -ge 1 ] || [[ $1 == "--help" ]] || [ $(id -u) -ne 0 ];then
	/show/messagebox "$0"
	/show/info "[release]"
	/show/usageDescription "remove notice to use raspi-config on connection"
	/show/usage '$0'
else
	/show/nlbecho "-> Remove raspi-config notice on bash startup" $OK
	if [ -e "/etc/profile.d/raspi-config.sh" ];then
		/show/minibox_OK
		rm -f /etc/profile.d/raspi-config.sh
	else
		/show/minibox_SKIP
	fi
fi