#!/bin/sh
if [ $# -ge 1 ] || [[ $1 == "--help" ]] || [ $(id -u) -ne 0 ];then
  /show/messagebox "$0"
  /show/info '[release] [reboot]'
  /show/usageDescription 'Expand SDcard on next boot using raspi-config unattended mode'
  /show/usage "$0"
else
	raspi-config --expand-rootfs
fi