#!/bin/bash
if [ $# -ge 1 ] || [[ $1 == "--help" ]] || [ $(id -u) -ne 0 ];then
	/show/messagebox "$0"
	/show/info '[alpha] [WIP] [danger] [dev]'
	/show/usageDescription 'Sync /boot/piget/config/external/* into /'
	/show/usage "$0"
else
	/show/listecho "Sync Configuration : user ==> LOCAL" $WARN
	cp -Rv /boot/piget/config/external/* /

	/show/listecho "Sync Configuration : boot ==> user" $WARN
	cp -R /boot/piget/config/ /user/config/piget
fi
