#!/bin/bash
if [ $# -ge 1 ] || [[ $1 == "--help" ]] || [ $(id -u) -ne 0 ];then
	/show/messagebox "$0"
	/show/info '[alpha] [WIP] [danger] [dev]'
	/show/usageDescription 'Sync backed-up configuration into /user'
	/show/usage "$0"
else

	/show/listecho "Sync Configuration : LOCAL ==> user" $WARN
	cd /user/config/piget/external

	FILES=$(find ./ -type f -name '*.*')

	for file in $FILES
	do
		cp -v ${file:1} /user/config/piget/external${file:1} 

	done

	/system/syncUserToBoot

fi
