#!/bin/bash
if [ $# -ge 1 ] || [[ $1 == "--help" ]] || [ $(id -u) -ne 0 ];then
	/show/messagebox "$0"
	/show/info '[alpha] [WIP] [danger] [dev]'
	/show/usageDescription 'Sync /user/config/piget/external/* into /'
	/show/usage "$0"
else
	/show/listecho "Sync Configuration : /user ==> LOCAL" $WARN
	cp -vR /user/config/piget/external/* /
	/system/syncUserToBoot

fi

