#!/bin/bash
if [ $# -ge 1 ] || [[ $1 == "--help" ]] || [ $(id -u) -ne 0 ];then
  /show/messagebox "$0"
  /show/info '[release] [interactive]'
  /show/usageDescription 'Modify timezone'
  /show/usage "$0"
else
	/show/description "Settings timezone"
	dpkg-reconfigure tzdata
fi