#!/bin/bash

if [ $# -ge 1 ] || [[ $1 == "--help" ]] || [ $(id -u) -ne 0 ];then
  /show/messagebox "$0"
  /show/info '[alpha] [caution]'
  /show/usageDescription 'Update all git repositories on the system'
  /show/usage "$0"
else
	/show/description "PIGET : Update all git repositories on the system"

	. /show/isConnected

	if [ $isConnected -eq 1 ];then

		find / -name .git -type d -prune | while read d; do
			d=$(dirname $d)
			if [ -d "$d" ]; then
			/show/nlbecho "-> UPDATE : $d" $OK   # your processing here
			
			cd "$d" && remoteUrl=$(cat ./.git/config |grep "url"|awk '{print $3}')
			cd "$d" && remoteHash=$(git ls-remote $remoteUrl|head -n1|awk '{print $1}')
			cd "$d" && localHash=$(git rev-parse origin/master)

			if [[ "$remoteHash" == "$localHash" ]];then
				/show/minibox_SKIP
			else
				cd "$d" && git fetch --all > /dev/null 2>&1 
				fetchStatus=$?
				cd "$d" && lastcomment=$(git reset --hard origin/master | awk '{$1="";$2="";$3="";$4="";$5="";print $0;}') > /dev/null 2>&1 
				resetStatus=$?
				cd "$d" && pullLog=$(git pull origin master) > /dev/null 2>&1 
				pullStatus=$?
				if [[ $fetchStatus -eq 0 ]] && [[ $resetStatus -eq 0 ]] && [[ $pullStatus -eq 0 ]];then
					/show/minibox_OK
					/show/colecho "COMMENT - $lastcomment"
				else
					/show/minibox_WARNING
					/show/colecho "Warning message from git pull" $WARN
					echo $pullLog
				fi
			fi
		fi
	done
	fi
fi