#!/bin/bash
export DEBIAN_FRONTEND=noninteractive
/show/isConnected

/show/description "Update everything"


/show/listecho "Update Applications with apt-get" $OK
#Update package
apt-get -q -y update
apt-get -q -y upgrade

/show/listecho "Update firmware with rpi-update" $OK
#Update firmware
/system/install rpi-update
rpi-update

/show/listecho "Update all git repositories" $OK
/pi/updateAllGitRepo
