#!/bin/bash

if [ $# -ge 3 ] || [ $# -le 1 ] || [[ $1 == "--help" ]] || [ $(id -u) -ne 0 ];then
	. /show/isConnected

	if [ $isConnected -eq 1 ];then
		/show/description "Update everything"
	
		/show/listecho "Update Applications with apt-get" $OK
		#Update package
		debconf-apt-progress -- apt-get -q -y update
		debconf-apt-progress -- apt-get -q -y upgrade

		/show/listecho "Update PiGet" $OK
		/pi/updatePiget
fi
