#!/bin/bash

if [ $# -eq 1 ] && [[ $1 == "--help" ]];then
	/show/messagebox "/net/internetOn"
	/show/usageDescription "change hostname (this will also change hostname for bonjour services)"
	/show/usage "/net/resetHost [NAME] (default:raspberrypi)"
	/show/example "/net/resetHost raspberrypi"
else
	. /string/ToNetbios $1
	NEW_HOSTNAME=$NewString
	/show/description "Bonjour Name : $NEW_HOSTNAME.local"
	/show/listecho "reset /etc/hostname" $OK
	/system/autoBackup /etc/hostname
	#Check if hostname is compatible with netbios
	echo $NEW_HOSTNAME > /etc/hostname

	/show/listecho "reset /etc/hosts" $OK
cat <<\EOF > /etc/hosts && 
127.0.0.1       localhost
::1             localhost ip6-localhost ip6-loopback
fe00::0         ip6-localnet
ff00::0         ip6-mcastprefix
ff02::1         ip6-allnodes
ff02::2         ip6-allrouters

127.0.1.1       TOREPLACE
EOF
	/string/replaceLine "/etc/hosts" "127.0.1.1" "127.0.1.1   $NEW_HOSTNAME" "ff02::2         ip6-allrouters"
	hostname $NEW_HOSTNAME
	/system/restart avahi-daemon

fi