#!/bin/bash
if [ $# -ge 2 ] || [[ $1 == "--help" ]] || [ $(id -u) -ne 0 ];then
	/show/messagebox $0
	/show/info "[beta] [/etc/networkg/interfaces] [network]"
	/show/usageDescription "Replace /etc/network/interfaces with default configuration"
	/show/usage "$0"
else
	cp /net/conf/interfaces /etc/network/interfaces
fi
