#!/bin/bash
if [ $# -ge 2 ] || [[ $1 == "--help" ]] || [ $(id -u) -ne 0 ];then
	/show/messagebox "/net/resetHost"
	/show/info "[beta] [network] [avahi] [bonjour]"
	/show/usageDescription "Change name in /etc/hosts and /etc/hostname"
	/show/usage "$0 [newname] (default:/boot/piget/config/name.txt)"
	/show/example "$0 raspberrypi"
	/show/return "NEW_HOSTNAME"
else
	#Check if name is a valid netbios name (for samba compatibility)
	. /string/ToNetbios $1
	NEW_HOSTNAME=$NewString
	

	# /show/listecho "Bonjour Name : $NEW_HOSTNAME.local" $OK

	# Change /etc/hostname 
	/system/autoBackup /etc/hostname
	echo $NEW_HOSTNAME > /etc/hostname

	# Change /etc/hosts	
cat <<EOF > /etc/hosts
127.0.0.1       localhost
::1             localhost ip6-localhost ip6-loopback
fe00::0         ip6-localnet
ff00::0         ip6-mcastprefix
ff02::1         ip6-allnodes
ff02::2         ip6-allrouters

127.0.1.1       $NEW_HOSTNAME
EOF
	hostname $NEW_HOSTNAME
	/system/restart avahi-daemon
fi