#!/bin/bash
if [ $# -eq 1 ];then
	port=$1
	exec 3<>/dev/tcp/127.0.0.1/$port
	read -r msg_in <&3
	echo $msg_in
else
	/show/messagebox "/net/socketSend"
	/show/usageDescription "Send text to a socket"
	/show/usage '/net/socketSend message port'
	/show/example '/net/socketSend "hello world" 9060'
fi
