#!/bin/bash
if [ $# -ne 1 ] || [[ $1 == "--help" ]] || [ $(id -u) -ne 0 ];then
	/show/messagebox $0
	/show/info "[exec] [socket] [local]"
	/show/usageDescription "Read a socket"
	/show/usage "$0 port"
	/show/example "$0 22"
else
	port=$1
	exec 3<>/dev/tcp/127.0.0.1/$port
	read -r msg_in <&3
	echo $msg_in
fi
