#!/bin/bash
if [ $# -ne 2 ] || [[ $1 == "--help" ]] || [ $(id -u) -ne 0 ];then
	/show/messagebox $0
	/show/info "[echo] [/dev/tcp] [local]"
	/show/usageDescription "Send a message to a socket"
	/show/usage "$0 message port"
	/show/example '/net/socketSend 22 "hello"'
else
	port=$1
	message=$2
	echo $message > /dev/tcp/127.0.0.1/$port
fi
