#!/bin/bash
/show/description "Use wifi (wlan0) as an hotspot"

/do/dhcpd/wlan0asHotSpot

#INTERFACES
/show/description "Configure wifi with static address (192.168.42.1)"

/show/listecho "Turn off wlan0" $OK
ifdown wlan0
/show/listecho "Modify /etc/network/interfaces" $OK
/system/autoBackup "/etc/network/interfaces"
cat <<\EOF > /etc/network/interfaces &&
# WIFI as HOTSPOT
auto lo

iface lo inet loopback
iface eth0 inet dhcp

allow-hotplug wlan0

iface wlan0 inet static
  address 192.168.42.1
  netmask 255.255.255.0

up iptables-restore < /etc/iptables.ipv4.nat
EOF

/show/listecho "move WPASupplicant.service"
mv -vf /usr/share/dbus-1/system-services/fi.epitest.hostap.WPASupplicant.service ~/

#HOSTAPD
/system/downloadModule hostapd
/do/hostapd/install
/do/hostapd/redirectTraffic

/show/listecho "Reset wlan0 to 192.168.42.1" $OK
ifconfig wlan0 192.168.42.1

/do/hostapd/start
