#!/bin/bash

/net/resetInterfaces
service stop isc-dhcp-server
service stop hostapd
/system/remove isc-dhcp-server
/system/remove hostapd
iptables -F
sh -c "echo 0 > /proc/sys/net/ipv4/ip_forward"
/string/replaceLineIfExists "/etc/sysctl.conf" "net.ipv4.ip_forward=1" "#net.ipv4.ip_forward=1"
ifdown wlan0
/show/listecho "move WPASupplicant.service"
mv -vf ~/fi.epitest.hostap.WPASupplicant.service /usr/share/dbus-1/system-services/
