#!/bin/bash
#From DougieLawson
#https://www.raspberrypi.org/forums/viewtopic.php?f=91&t=109034&hilit=+mt7601#p749749
/show/description "Installing driver for wifi"
wget $(echo "https://dl.dropboxusercontent.com/u/80256631/mt7601-"`uname -r | awk '{sub(/\+/,"")}{print}'`"-"`uname -v | awk '{sub (/#/,"")}{print $1}'`).tar.gz -O /tmp/wifiDriver.tar.gz
tar -xvf /tmp/wifiDriver.tar.gz -C /tmp/
/tmp/install.sh

